name: Variable test

on:
  push

env:
  GLOBAL_VAR: "This is a global variable"

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      foo_output: ${{ steps.set-output.outputs.foo_output }}
    steps:
      - name: Print global variable
        run: echo $GLOBAL_VAR
      - name: Create variables
        run: |
          chmod +x .github/scripts/create_variable.sh
          ./.github/scripts/create_variable.sh
      - name: Use the environment variables
        run: |
          echo "FOO is $FOO"
          echo "BAR is $BAR"
      - name: Create output
        id: set-output
        run: |
          chmod +x .github/scripts/create_output.sh
          ./.github/scripts/create_output.sh
  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      FOO_OUTPUT: ${{ needs.job1.outputs.foo_output }}
    steps:
      - name: Print global variable
        run: echo $GLOBAL_VAR
      - name: Try to use environment variables from previous job
        run: |
          echo "FOO is $FOO"
          echo "BAR is $BAR"
